### ISSUE TITLE
Feature Request: Playlist for each mapper you follow

### ISSUE THREAD

**Issue by thezeagar** [brian91292/SyncSaber#1]
Would it be possible to add the option to auto generate a separate playlist for each mapper you have followed or in your favoritemappers file?

Example: I currently have syncsaber downloading all maps from Bennydabeast, Freeek, and Joetastic. Once playlists are working again, it would be great if I could load up a playlist of just Joetastic's or Benny's maps.

**Comment by brian91292** [comment]
Will consider this, seems like it could be useful. I'm definitely planning to add some more playlists to help sort out what gets downloaded, and this seems like a good idea.

**Comment by brian91292** [comment]
Added this today:
https://github.com/brian91292/SyncSaber/commit/90a9452c83deacc530a8187eb5138ad3e4ab8d09
