### ISSUE TITLE
bug: when song list is sorted by "newest", after syncsaber updates a song it causes the song list to jump back to the top

### ISSUE THREAD

**Issue by telos00** [brian91292/SyncSaber#6]
1. have the song list sorted by newest
2. scroll down the list until you hit a song that syncsaber updates.
3. after syncsaber updates the song, the whole list is re-sorted, with the updated song at the top. the cursor is repositioned to the top of the list.

-- the problem here is that the cursor jumps back to the top of the list along with the updated song. so as you scroll down the list, you'll randomly be thrown back to the top when you hit a song that needs updating.
-- this makes navigating a long list of songs (sorted by newest) painful.
-- can syncsaber leave the song position alone after an update, or if the list has to be re-sorted, put the cursor back where it was in the list (like pointing at the song after the song that was updated) instead of jumping back to the top.

**Comment by brian91292** [comment]
This is an issue with song loader, downloader, or browser. Not sure which one, but it's not an issue with syncsaber.
