### ISSUE TITLE
cant enter username + other

### ISSUE THREAD

**Issue by seethingword** [brian91292/SyncSaber#7]
For some reason i cant enter my username in menu and none of the settings save

**Comment by filipegorges** [comment]
I've been experiencing the same issue, have you found anything yet?

**Comment by seethingword** [comment]
no nothing yet

**Comment by seethingword** [comment]
no nothing yet

**Comment by balkyne** [comment]
This problem began when Beat Saber was updated to version 1.0.0. The creator is yet to update the application to be compatible with the new game, now it is out of early access

**Comment by seethingword** [comment]
Just found out from the modding group that syncsaber no longer works.

**Comment by brian91292** [comment]
Not sure if this is still an issue but since the mod wasn't updated at the time of creation I'm guessing this is no longer an issue.
