### ISSUE TITLE
Unable to add beastsaber username

### ISSUE THREAD

**Issue by weazul** [brian91292/SyncSaber#8]
There isn't an option to add the username in game, and when i try to edit the JSON file it resets to default whenever BeatSaber opens

**Comment by Darkrael** [comment]
You are probably using the wrong syntax. Since your username is a string you need to put it in quotation marks. The line with your username should look like this:
"BeastSaberUsername": "USERNAME",
with USERNAME replaced by your actual username

**Comment by weazul** [comment]
thank you, that worked, no ones been able to answer this question of mine for months from either the modsaber discord or from when im streaming it. thank you
